import Head from "next/head";
import { Posts } from "../src/content";
import DisplayPreview from "../src/components/DisplayPreview";
import { Box } from "@chakra-ui/react";
import Intro from "../src/components/Intro";

const Home = () => {
  const data = Posts;
  return (
    <>
      <Head>
        <title>Nick Foden</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box display="flex" margin={8} flexWrap="wrap">
          {data.map((content) => (
            <DisplayPreview key={content.slug} content={content} />
          ))}
        </Box>
      </main>
    </>
  );
};

export default Home;
